[project]
name = "videogui"
version = "0.1.1"
requires-python = ">=3.10"
dependencies = []

[project.scripts]
videogui = "videogui.launch:main"
videogui-gui = "videogui.gui:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pyright>=1.1.409",
]
